### ISSUE TITLE
Testing new process info discovery 

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1607]
## Notes
- [x] Ensure the race detector is enabled
- [x] Check on Parca
- [x] Check also on Polar Signals
- [x] Check for stack traces correctness (i.e., before vs after in differential flame graphs)

## Runtimes
- [x] Go
- [x] Native code (not Go) with debug info not extracted
- [x] Native code (not Go) with extracted debug info
- [x] Native code with debuginfo only in debuginfod servers
- [x] JIT
- [x] jitdump

## Important software
- [x] MySQL
- [x] Postgres
- [x] Redpanda
- [x] Short-lived Go procs (https://github.com/parca-dev/parca-agent/issues/1619)
- [x] Short-lived native (not Go) procs (https://github.com/parca-dev/parca-agent/issues/1619)

## Check:
- [x] Normalization errors
- [x] Other added metrics
- [x] Error logs
- [x] Logs that are too verbose by default
- [x] Symbolization 
- [x] Open file descriptors (ensure there are no leaks)
- [x] CPU and memory shouldn't regress (https://github.com/parca-dev/parca-agent/issues/1616)

## Issues found in Demo / Prod:

cc/ @kakkoyun

**Comment by asubiotto** [comment]
These are one-time manual tests, correct? Is this change also tested with unit/integration tests?

**Comment by kakkoyun** [comment]
> These are one-time manual tests, correct? Is this change also tested with unit/integration tests?

There are one-time tests. It would be nice to have integration/regression tests for these eventually.

**Comment by kakkoyun** [comment]
@javierhonduco If I remember correctly, you had an app to reproduce short-lived processes?

**Comment by javierhonduco** [comment]
@kakkoyun For frame pointers: https://github.com/parca-dev/testdata/blob/main/src/main.go

**Comment by kakkoyun** [comment]
FYI Updating the issue as test (ticking the boxes)

**Comment by kakkoyun** [comment]
MySQL: https://pprof.me/53340c1

![CleanShot 2023-06-16 at 16 05 19](https://github.com/parca-dev/parca-agent/assets/536449/e8cdbd83-9cdc-4e44-b53f-5aea9fa3f692)

**Comment by kakkoyun** [comment]
Postgres: https://pprof.me/585c5f1

![CleanShot 2023-06-16 at 16 10 56](https://github.com/parca-dev/parca-agent/assets/536449/46909508-4278-4b2c-a3f7-65a11bf979f3)

**Comment by kakkoyun** [comment]
Redpanda: https://pprof.me/faf4ab0 (On a 4-node local cluster)

![CleanShot 2023-06-16 at 16 39 48](https://github.com/parca-dev/parca-agent/assets/536449/22243de1-bbfb-40bb-b734-3e1b16dcda82)
