### ISSUE TITLE
Add ability to specify targets to profile

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#690]
~~This issue is about bringing back the functionality specified by ` --pod-label-selector` and `--systemd-units` flags we had from the last major release.~~

```
      --pod-label-selector=STRING
                                  Label selector to control which Kubernetes
                                  Pods to select.
      --cgroups=CGROUPS,...       Cgroups to profile on this node.
      --systemd-units=SYSTEMD-UNITS,...
                                  [deprecated, use --cgroups instead] systemd
                                  units to profile on this node.
```

It's removed as part of #627, and the fully featured filtering will be added eventually.

# Tasks

- [x] As an initial implementation, let profiler to capture profiles but just do not send them to the server
- [x] Specify pods to profile
- [x] Specify systemd units to profile
- [x] Specify any target to profile
- [ ] Reject the events in eBPF level if the PID is not as part of a desired target

Related #7

https://github.com/parca-dev/parca-agent/pull/887 covers almost all of the intended behavior, so we don't need half-measures for now. We need to update the documentation and provide samples of configuration to demonstrate the functionality is equivalent to the flags.

**Comment by kakkoyun** [comment]
Closing for the sake of https://github.com/parca-dev/parca-agent/pull/887
